# Generated by Django 4.0.1 on 2022-02-12 16:15

from django.db import migrations, models
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentor',
            options={'ordering': ['name', 'email']},
        ),
        migrations.RemoveField(
            model_name='student',
            name='number_telephone',
        ),
        migrations.AddField(
            model_name='student',
            name='number_phone',
            field=models.CharField(blank=True, max_length=11, validators=[registration.models.validators_number_phone], verbose_name='Enter your phone'),
        ),
    ]
