# Generated by Django 4.0.2 on 2022-02-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentschedules',
            name='sick',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
