# Generated by Django 4.0.1 on 2022-02-14 10:12

from django.db import migrations, models
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_mentor_options_remove_student_number_telephone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='number_phone',
            field=models.CharField(blank=True, max_length=11, validators=[registration.models.validators_number_phone]),
        ),
    ]
