# Generated by Django 4.0.2 on 2022-02-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_studentschedules_sick'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentschedules',
            name='sick',
        ),
        migrations.AddField(
            model_name='schedules',
            name='sick',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
