# Generated by Django 4.0.1 on 2022-02-14 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_alter_student_number_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'permissions': (('can_masscreate_tag', 'can masscreate tag'),)},
        ),
    ]
