# Generated by Django 4.0.2 on 2022-02-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_remove_studentschedules_sick_schedules_sick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentschedules',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
