# Generated by Django 4.0.2 on 2022-03-14 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_alter_studentschedules_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentschedules',
            old_name='names',
            new_name='student',
        ),
        migrations.RemoveField(
            model_name='studentschedules',
            name='days',
        ),
        migrations.AddField(
            model_name='studentschedules',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.schedules'),
        ),
    ]
