# Generated by Django 4.0.1 on 2022-02-14 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_alter_student_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'permissions': (('take_information', 'take information'),)},
        ),
    ]
