# Generated by Django 4.0.2 on 2022-02-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='access',
        ),
        migrations.RemoveField(
            model_name='node',
            name='inprogress',
        ),
        migrations.RemoveField(
            model_name='node',
            name='ready',
        ),
        migrations.AddField(
            model_name='node',
            name='deadline',
            field=models.IntegerField(default=7),
        ),
    ]
